In [1]:
100 / 7

14.285714285714286

In [2]:
100 // 7

14

In [3]:
500 * (.2 * 1.27)

127.0

In [4]:
pi = 3.141592653589793238

In [5]:
pi

3.141592653589793

In [6]:
type(pi)

float

In [7]:
bool([])

False

In [1]:
yet_another_pun = '''Son: "Dad, can you tell me what a solar eclipse is?" Dad: "No Sun."'''

In [2]:
yet_another_pun

'Son: "Dad, can you tell me what a solar eclipse is?" Dad: "No Sun."'

In [3]:
multiline_str = """a
b"""
multiline_str

'a\nb'

In [4]:
len(multiline_str)

3

In [5]:
list(multiline_str)

['a', '\n', 'b']

In [6]:
today = "Sunday"

In [7]:
today[0]

'S'

In [8]:
today[7]

IndexError: string index out of range

In [9]:
today[-1]

'y'

In [10]:
today[1:5]

'unda'

In [11]:
today[0:-1]

'Sunda'

In [12]:
today[0:-2]

'Sund'

In [13]:
tomorrow = today.replace("Sun", "Mon")

In [14]:
tomorrow

'Monday'

In [15]:
"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(",")

['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

In [16]:
"Sun Mon Tue Wed Thu Fri Sat".split(" ")

['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

In [17]:
the_3_musketeers = ["Athos", "Porthos", "Aramis"]
str(the_3_musketeers)

"['Athos', 'Porthos', 'Aramis']"

In [18]:
the_3_musketeers

['Athos', 'Porthos', 'Aramis']

In [21]:
fruits = ['apple', 'banana', 'cherry']
a_list = [23, 'hello', None, 3.14, fruits, 3 <= 5]
a_list
#type(a_list)

[23, 'hello', None, 3.14, ['apple', 'banana', 'cherry'], True]

In [22]:
len(a_list)

6

In [24]:
fruits.append('dates')
fruits

['apple', 'banana', 'cherry', 'dates', 'dates']

In [25]:
fruits.remove('blueberry')

ValueError: list.remove(x): x not in list

In [26]:
fruits.remove('dates')

In [27]:
fruits

['apple', 'banana', 'cherry', 'dates']

In [28]:
fruits.pop(2)
fruits

['apple', 'banana', 'dates']

In [29]:
a_list

[23, 'hello', None, 3.14, ['apple', 'banana', 'dates'], True]

In [30]:
'pineapple' in fruits

False

In [31]:
['apple', 'banana', 'dates'] in a_list

True

In [32]:
#To combine two or more lists, use the + operator. This operation is also called concatenation.
more_fruits = fruits + ['pineapple', 'tomato', 'guava'] + ['dates', 'banana']
more_fruits

['apple', 'banana', 'dates', 'pineapple', 'tomato', 'guava', 'dates', 'banana']

In [33]:
more_fruits.pop(2)

'dates'

In [34]:
more_fruits

['apple', 'banana', 'pineapple', 'tomato', 'guava', 'dates', 'banana']

In [35]:
more_fruits.remove('banana')
more_fruits

['apple', 'pineapple', 'tomato', 'guava', 'dates', 'banana']

In [36]:
more_fruits.reverse()

In [37]:
more_fruits

['banana', 'dates', 'guava', 'tomato', 'pineapple', 'apple']

In [40]:
ext_list = ['banana', 'dates', 'guava', 'tomato', 'pineapple', 'apple']
picked_list = ['toyota', 'google', 'facebook', 'amazon', 'neflix', 'nvidia']
ext_list.extend(picked_list)
ext_list

['banana',
 'dates',
 'guava',
 'tomato',
 'pineapple',
 'apple',
 'toyota',
 'google',
 'facebook',
 'amazon',
 'neflix',
 'nvidia']

In [41]:
ext_list.sort()

In [42]:
ext_list

['amazon',
 'apple',
 'banana',
 'dates',
 'facebook',
 'google',
 'guava',
 'neflix',
 'nvidia',
 'pineapple',
 'tomato',
 'toyota']

In [43]:
num_list = [3,4,12,56,7,8,12,45,0,34,3456,23]
num_list

[3, 4, 12, 56, 7, 8, 12, 45, 0, 34, 3456, 23]

In [44]:
num_list = [3,4,12,56,7,8,12,45,0,34,3456,23]
num_list.sort(reverse=False)
num_list

[0, 3, 4, 7, 8, 12, 12, 23, 34, 45, 56, 3456]

In [46]:
num_list.sort(reverse=True)
num_list

[3456, 56, 45, 34, 23, 12, 12, 8, 7, 4, 3, 0]

In [47]:
a_list

[23, 'hello', None, 3.14, ['apple', 'banana', 'dates'], True]

In [56]:
a_list[2 : len(a_list)]
#len(a_list)

[None, 3.14, ['apple', 'banana', 'dates'], True]

In [58]:
a_list[22: 20]

[]

In [59]:
a_list[:5]

[23, 'hello', None, 3.14, ['apple', 'banana', 'dates']]

In [60]:
a_list[3:]

[3.14, ['apple', 'banana', 'dates'], True]

In [61]:
a_list[:]

[23, 'hello', None, 3.14, ['apple', 'banana', 'dates'], True]

In [63]:
a_list[-2:-5]

[]

In [64]:
a_list[-5:-2]

['hello', None, 3.14]

In [72]:
a_tuple = 23, "hello", False, None, 23, 37, "hello"
help(a_tuple.index)

Help on built-in function index:

index(value, start=0, stop=9223372036854775807, /) method of builtins.tuple instance
    Return first index of value.
    
    Raises ValueError if the value is not present.



In [74]:
a_tuple.index(None)

3

In [75]:
person1 = {
        'name': 'John Doe',
        'sex': 'Male',
        'age': 32,
        'married': True
    }

In [76]:
person1

{'name': 'John Doe', 'sex': 'Male', 'age': 32, 'married': True}

In [77]:
list(person1)

['name', 'sex', 'age', 'married']

In [78]:
type(person1.keys())

dict_keys

In [80]:
person1[list(person1)[1]]

'Male'

In [81]:
person2 = {'name':'John', 'gender':'Male', 'addr':'Japan', 'addr':'Chengdu'}

In [82]:
person2

{'name': 'John', 'gender': 'Male', 'addr': 'Chengdu'}

In [83]:
person3 = person2
person3['name'] = 'Jiangjiefeng'

In [84]:
person3

{'name': 'Jiangjiefeng', 'gender': 'Male', 'addr': 'Chengdu'}

In [85]:
person2

{'name': 'Jiangjiefeng', 'gender': 'Male', 'addr': 'Chengdu'}

In [86]:
person4 = person2.copy()
person4['gender'] = 'unknown'

In [87]:
person4

{'name': 'Jiangjiefeng', 'gender': 'unknown', 'addr': 'Chengdu'}

In [88]:
person2

{'name': 'Jiangjiefeng', 'gender': 'Male', 'addr': 'Chengdu'}

In [93]:
property1 = {'car':'Ford', 'deposit': 1000000}
person5 = {'name':'John', 'gender':'Male', 'property':property1, 'addr':'Chengdu'}

In [94]:
person5

{'name': 'John',
 'gender': 'Male',
 'property': {'car': 'Ford', 'deposit': 1000000},
 'addr': 'Chengdu'}

In [95]:
person5['property']['deposit']

1000000

In [99]:
x = ('name', 'gender', 'property')
y = ''
thisdict = dict.fromkeys(x, y)
thisdict

{'name': '', 'gender': '', 'property': ''}

In [100]:
person5.update({'title':'Engineer'})
person5

{'name': 'John',
 'gender': 'Male',
 'property': {'car': 'Ford', 'deposit': 1000000},
 'addr': 'Chengdu',
 'title': 'Engineer'}

In [101]:
skill_set = {'Java':'None', 'Python':'Good', 'C/C++':'Expert'}
person5.update({'Python':skill_set['Python']})
person5

{'name': 'John',
 'gender': 'Male',
 'property': {'car': 'Ford', 'deposit': 1000000},
 'addr': 'Chengdu',
 'title': 'Engineer',
 'Python': 'Good'}

In [102]:
person5.pop('Python')
person5

{'name': 'John',
 'gender': 'Male',
 'property': {'car': 'Ford', 'deposit': 1000000},
 'addr': 'Chengdu',
 'title': 'Engineer'}

In [103]:
person5.update(skill_set)
person5

{'name': 'John',
 'gender': 'Male',
 'property': {'car': 'Ford', 'deposit': 1000000},
 'addr': 'Chengdu',
 'title': 'Engineer',
 'Java': 'None',
 'Python': 'Good',
 'C/C++': 'Expert'}

In [104]:
my_books = {1:'good book', 2:'no_book', True:'be my guest'}

In [105]:
my_books

{1: 'be my guest', 2: 'no_book'}

In [111]:
another_number = 36
if another_number % 2 == 0:
    print('The given number {} is even.'.format(another_number))
else:
    print('what a wrong decision!')

The given number 36 is even.


In [114]:
line = '*'
max_length = 10

while len(line) < max_length:
    print(line)
    line += "*"
    
while len(line) > 0:
    print(line)
    line = line[:-1]

*
**
***
****
*****
******
*******
********
*********
**********
*********
********
*******
******
*****
****
***
**
*


In [117]:
max_length = 6
space = '     '
line = '*'
while line.count('*') < max_length:
    print(space+line)
    space = space[:-1]
    line += '*'
while line.count('*') > 0:
    print(space+line)
    space += ' '
    line = line[:-1]

     *
    **
   ***
  ****
 *****
******
 *****
  ****
   ***
    **
     *


In [119]:
max_length = 11
space = '     '
line = '*'
while line.count('*') < max_length:
    print(space+line+space)
    space = space[:-1]
    line += '**'
while line.count('*') > 0:
    print(space+line+space)
    space += ' '
    line = line[1:-1]

     *     
    ***    
   *****   
  *******  
 ********* 
***********
 ********* 
  *******  
   *****   
    ***    
     *     


In [1]:
import math

In [2]:
math.sqrt(49)

7.0

In [4]:
math.ceil(49.1)

50

In [6]:
math.floor(56.7)

56

In [10]:
tests = []
# query occurs in the middle
tests.append(test)

tests.append({
    'input': {
        'cards': [13, 11, 10, 7, 4, 3, 1, 0],
        'query': 1
    },
    'output': 6
})
# query is the first element
tests.append({
    'input': {
        'cards': [4, 2, 1, -1],
        'query': 4
    },
    'output': 0
})
# query is the last element
tests.append({
    'input': {
        'cards': [3, -1, -9, -127],
        'query': -127
    },
    'output': 3
})
# cards contains just one element, query
tests.append({
    'input': {
        'cards': [6],
        'query': 6
    },
    'output': 0 
})
# cards does not contain query 
tests.append({
    'input': {
        'cards': [9, 7, 5, 2, -9],
        'query': 4
    },
    'output': -1
})
# cards is empty
tests.append({
    'input': {
        'cards': [],
        'query': 7
    },
    'output': -1
})
# numbers can repeat in cards
tests.append({
    'input': {
        'cards': [8, 8, 6, 6, 6, 6, 6, 3, 2, 2, 2, 0, 0, 0],
        'query': 3
    },
    'output': 7
})
# query occurs multiple times
tests.append({
    'input': {
        'cards': [8, 8, 6, 6, 6, 6, 6, 6, 3, 2, 2, 2, 0, 0, 0],
        'query': 6
    },
    'output': 2
})

def locate_card(cards, query):
    # Create a variable position with the value 0
    position = 0
    
    # Set up a loop for repetition
    while True:
        
        # Check if element at the current position matche the query
        if cards[position] == query:
            
            # Answer found! Return and exit..
            return position
        
        # Increment the position
        position += 1
        
        # Check if we have reached the end of the array
        if position == len(cards):
            
            # Number not found, return -1
            return -1

"""
Arbitrary Arguments, *args
If you do not know how many arguments that will be passed into your function, add a * before the parameter name in the function definition.
This way the function will receive a tuple of arguments, and can access the items accordingly:
Arbitrary Keyword Arguments, **kwargs
If you do not know how many keyword arguments that will be passed into your function, add two asterisk: ** before the parameter name in the function definition.
This way the function will receive a dictionary of arguments, and can access the items accordingly:
"""
#locate_card(**test['input']) == test['output']
test = {
    'input': { 
        'cards': [13, 11, 10, 7, 4, 3, 1, 0], 
        'query': 7
    },
    'output': 3
}
#result = locate_card(test['input']['cards'], test['input']['query'])
result = locate_card(**test['input'])
result

3

In [17]:
"""
    Modules: Modules are files containing Python code (variables, functions, classes, etc.). They provide a way of organizing the code for large Python projects into files and folders. The key benefit of using modules is namespaces: you must import the module to use its functions within a Python script or notebook. Namespaces provide encapsulation and avoid naming conflicts between your code and a module or across modules.
    """

import math

def loan_emi(amount, duration, rate, down_payment=0):
    """Calculates the equal montly installment (EMI) for a loan.
    
    Arguments:
        amount - Total amount to be spent (loan + down payment)
        duration - Duration of the loan (in months)
        rate - Rate of interest (monthly)
        down_payment (optional) - Optional intial payment (deducted from amount)
    """
    loan_amount = amount - down_payment
    try:
        emi = loan_amount * rate * ((1+rate)**duration) / (((1+rate)**duration)-1)
    except ZeroDivisionError:
        print("you were trying to divide by zero!")
        emi = loan_amount / duration
    emi = math.ceil(emi)    
    return emi

emi1 = loan_emi(
    amount=1260000, 
    duration=8*12, 
    rate=0.1/12, 
    down_payment=3e5
)
emi2 = loan_emi(amount=1260000, duration=10*12, rate=.0)
print(emi1, emi2)

you were trying to divide by zero!
14568 10500


In [12]:
cost_of_house = 800000
home_loan_duration = 6*12 # months
home_loan_rate = 0.07/12 # monthly
home_down_payment = .25 * 800000

emi_house = loan_emi(amount=cost_of_house,
                     duration=home_loan_duration,
                     rate=home_loan_rate, 
                     down_payment=home_down_payment)

emi_house

10230

In [13]:
cost_of_car = 60000
car_loan_duration = 1*12 # months
car_loan_rate = .12/12 # monthly

emi_car = loan_emi(amount=cost_of_car, 
                   duration=car_loan_duration, 
                   rate=car_loan_rate)

emi_car

5331

In [53]:
cities = ["Paris", "London", "Dubai", "Mumbai"]
return_flights = {"Paris":200, "London":250, "Dubai":370, "Mumbai":450}
hotels_per_day = {"Paris":20, "London":30, "Dubai":15, "Mumbai":10}
weekly_car_rentals = {"Paris":200, "London":120, "Dubai":80, "Mumbai":70}

def cost_of_trip(city, flight, hotel_cost, car_rent, num_of_days = 7):
    total_amount = (flight + 
        hotel_cost * num_of_days + 
        car_rent * math.ceil(num_of_days / 7))
    return total_amount

days = 14
total_costs = []
for city in cities:
    city_cost = cost_of_trip(city, return_flights[city], hotels_per_day[city], 
            weekly_car_rentals[city], days)
    total_costs.append((city_cost, city))
    print("{}'s vacation {} days cost: ${}".format(city, days, city_cost))

print("Minium cost for {0}'s vacation is {1} ${2}".format(days, min(total_costs)[1], min(total_costs)[0]))


Paris's vacation 14 days cost: $880
London's vacation 14 days cost: $910
Dubai's vacation 14 days cost: $740
Mumbai's vacation 14 days cost: $730
Minium cost for 14's vacation is Mumbai $730


In [29]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity, itemno, price))

I want to pay 49.95 dollars for 3 pieces of item 567.


In [1]:
# test uploading behind the wall

In [2]:
w1,w2,w3 = 0.3,0.2,0.5

In [3]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43
kanto_yield_apples = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3
kanto_yield_apples

56.8

In [4]:
print("The expected yeild of apples in Kanto region is {} tons per hectare.".format(kanto_yield_apples))

The expected yeild of apples in Kanto region is 56.8 tons per hectare.


In [7]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]
weights = [w1, w2, w3]
"""
首先，zip()函数是一个迭代器（即遍历的意思），会将多个对象数据对应位置的数据放在元组里并返回一个对象。
kanto   = [73,  67,  43]
weights = [0.3, 0.2, 0.5]
"""
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result
list(zip(kanto, weights))

[(73, 0.3), (67, 0.2), (43, 0.5)]

In [8]:
crop_yield(johto, weights)

76.9

In [9]:
crop_yield(unova, weights)

74.9

In [10]:
import numpy as np

In [11]:
# Numpy arrays have the type ndarray.
kanto = np.array([73, 67, 43])
weights = np.array([0.3, 0.2, 0.5])
np.dot(kanto, weights)

56.8

In [12]:
"""
We can achieve the same result with low-level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the resulting numbers' sum.
"""
(kanto * weights).sum()

56.8

In [13]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
# 2D array (matrix)
climate_data.shape

(5, 3)

In [14]:
weights

array([0.3, 0.2, 0.5])

In [16]:
weights.shape

(3,)

In [17]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]],
     
    [[15, 16, 17], 
     [17, 18, 19.5]]])
arr3.shape

(2, 2, 3)

In [18]:
#We can use the np.matmul() function or the @ operator to perform matrix multiplication.
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [19]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [21]:
#To read this file into a numpy array, we can use the genfromtxt function.
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1c0f0201d60>)

In [22]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [23]:
climate_data.shape

(10000, 3)

In [24]:
weights.shape

(3,)

In [25]:
yields = climate_data @ weights
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [26]:
#Let's add the yields to climate_data as a fourth column using the np.concatenate function.
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [27]:
arr_a = np.array([
        [0, 1, 3],
        [5, 7, 9]
        ])
arr_b = np.array([
        [0, 2, 4],
        [6, 8, 10]
        ])

arr_con_axis_0 = np.concatenate((arr_a, arr_b), axis = 0)
arr_con_axis_0

array([[ 0,  1,  3],
       [ 5,  7,  9],
       [ 0,  2,  4],
       [ 6,  8, 10]])

In [28]:
arr_con_axis_1 = np.concatenate((arr_a, arr_b), axis = 1)
arr_con_axis_1

array([[ 0,  1,  3,  0,  2,  4],
       [ 5,  7,  9,  6,  8, 10]])

In [29]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [38]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])
arr3[:2, 1]

array([[13., 14., 15., 19.],
       [63., 92., 36., 18.]])

In [44]:
arr_2d_test = np.array([
    [0, 1, 2, 3, 4, 5], 
    [10, 11, 12, 13, 14, 15], 
    [20, 21, 22, 23, 24, 25], 
    [30, 31, 32, 33, 34, 35], 
    [40, 41, 42, 43, 44, 45],      
    [50, 51, 52, 53, 54, 55]])
arr_2d_test[0, 3:5]
arr_2d_test[4:, 4:]
arr_2d_test[2::2, ::2]
arr_2d_test[:, 2]

array([ 2, 12, 22, 32, 42, 52])

In [15]:
from sys import getsizeof
import numpy as np
arr_null = np.zeros(shape=(10,))
print(getsizeof(arr_null))
arr_null.nbytes

184


80

In [10]:
type(arr_null[0])

numpy.float64

In [19]:
np.info(np.zeros)

zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. versionadded:

In [97]:
import os
os.listdir('.')

['.git',
 'climate.csv',
 'climate.txt',
 'climate_results.txt',
 'demo.ipynb',
 'index.html',
 'NumpyLearning',
 'PandasLearning',
 'PMLLKeys',
 'PMLLKeys.pub',
 'PyLearning.ipynb',
 'README.md']

In [98]:
os.makedirs('./data', exist_ok=True)

In [99]:
'data' in os.listdir('.')

True

In [100]:
os.listdir('./data')

[]

In [101]:
url1 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans1.txt'
url2 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans2.txt'
url3 = 'https://gist.githubusercontent.com/aakashns/257f6e6c8719c17d0e498ea287d1a386/raw/7def9ef4234ddf0bc82f855ad67dac8b971852ef/loans3.txt'
from urllib.request import urlretrieve
urlretrieve(url1, './data/loans1.txt')

('./data/loans1.txt', <http.client.HTTPMessage at 0x149e11d8e80>)

In [104]:
urlretrieve(url2, './data/loans2.txt')

('./data/loans2.txt', <http.client.HTTPMessage at 0x149e11d85e0>)

In [105]:
urlretrieve(url3, './data/loans3.txt')

('./data/loans3.txt', <http.client.HTTPMessage at 0x149dfff0280>)

In [106]:
file1 = open('./data/loans1.txt', mode='r')

In [107]:
file1

<_io.TextIOWrapper name='./data/loans1.txt' mode='r' encoding='UTF-8'>

In [108]:
file1_contents = file1.read()
print(file1_contents)

amount,duration,rate,down_payment
100000,36,0.08,20000
200000,12,0.1,
628400,120,0.12,100000
4637400,240,0.06,
42900,90,0.07,8900
916000,16,0.13,
45230,48,0.08,4300
991360,99,0.08,
423000,27,0.09,47200


In [109]:
file1.close()

In [110]:
with open('./data/loans2.txt') as file2:
    file2_contents = file2.read()
    print(file2_contents)


amount,duration,rate,down_payment
828400,120,0.11,100000
4633400,240,0.06,
42900,90,0.08,8900
983000,16,0.14,
15230,48,0.07,4300


In [111]:
with open('./data/loans3.txt', 'r') as file3:
    file3_lines = file3.readlines()
file3_lines

['amount,duration,rate,down_payment\n',
 '45230,48,0.07,4300\n',
 '883000,16,0.14,\n',
 '100000,12,0.1,\n',
 '728400,120,0.12,100000\n',
 '3637400,240,0.06,\n',
 '82900,90,0.07,8900\n',
 '316000,16,0.13,\n',
 '15230,48,0.08,4300\n',
 '991360,99,0.08,\n',
 '323000,27,0.09,4720010000,36,0.08,20000\n',
 '528400,120,0.11,100000\n',
 '8633400,240,0.06,\n',
 '12900,90,0.08,8900']

In [112]:
def parse_headers(header_line):
    return header_line.strip().split(',')
file3_lines[0]

'amount,duration,rate,down_payment\n'

In [113]:
headers = parse_headers(file3_lines[0])
headers

['amount', 'duration', 'rate', 'down_payment']

In [3]:
def parse_values(data_line):
    values = []
    for item in data_line.strip().split(','):
        if item == '':
            values.append(0.0)
        else:
            try:
                values.append(float(item))
            except ValueError:
                values.append(item)
    return values
file3_lines[1]
print(parse_values(file3_lines[1]))

NameError: name 'file3_lines' is not defined

In [118]:
file3_lines[2]
parse_values(file3_lines[2])

[883000.0, 16.0, 0.14, 0.0]